# Run this app with `python app.py` and
# visit http://127.0.0.1:8050/ in your web browser.

import dash
from dash import dcc
from dash import html
import plotly.express as px
import pandas as pd
import dash_bootstrap_components as dbc
from dash.dependencies import Input, Output
import os
from itertools import chain
from collections import Counter

from app import app


# Change working directory to script location
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)


df = pd.read_csv("../datasets/final_tweets.csv")
df['new_tweet_text'] = df['new_tweet_text'].astype(str)

# Load LDA
lda_node = html.Iframe(src=app.get_asset_url("ldavis_prepared_4.html"),
    style=dict(position="absolute", 
                # margin= "5rem 2rem 0rem 18rem",
                # padding= "2rem 1rem",
                width="100%", 
                height="100%"))


# Layout
layout = html.Div([
    html.H2('LDA Topic Model',
            style={'textAlign':'center'}),
    html.Hr(),
    html.P(
        children="This section shows the common features in Tweets before and during the pandemic using LDA topic model.",
        style={'textAlign': 'center'},
        className="lead"
    ),
    html.Br(),
    dbc.Card(
        dcc.Markdown('''
        #### LDA (Latent Dirichlet Allocation) Topic Model Visualisation

        Topic modelling is one of the statistical language models that cluster words for a set of corpuses. 
        It is a useful model for revealing hidden pattern or structure from the text data. 
        If often be used in Natural Language Processing (NLP) to find common text terms and to reveal hidden relationship between word and the documents. 
        Here implements LDA, a topic model, to determine common themes or features in the whole corpus (the collected Tweets). 

        Method to interpret the graph below:
        * Each bubble represents a topic. The larger the bubble, the higher percentage of the number of tweets in the corpus is about that topic.
        * Blue bars represent the overall frequency of each word in the corpus. If no topic is selected, the blue bars of the most frequently used words will be displayed.
        * Red bars give the estimated number of times a given term was generated by a given topic. 
        '''
        ),
        body=True, color="success", outline=True,className="mb-3"
    ),
    lda_node
    

])


# @app.callback(
#     Output("page-content", "children"),
#     [Input("url", "pathname")]
# )